steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/industrial-joy-185100/gcp-cd-codelab:latest']
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/industrial-joy-185100/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "--cache-from', 'gcr.io/industrial-joy-185100/gcp-cd-codelab:latest","."]
images:
  - "gcr.io/industrial-joy-185100/gcp-cd-codelab:$REVISION_ID"
timeout: 900s