steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://rust-dependencies/target.zip", "previous_target.zip"]
  - name: "ubuntu"
    args: ["unzip", "previous_target.zip"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/custom-script-test", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/industrial-joy-185100/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "new_target.zip", "gs://rust-dependencies/target.zip"]
images:
  - "gcr.io/industrial-joy-185100/gcp-cd-codelab:$REVISION_ID"
timeout: 900s